package kr.lunaf.varstore.api;

/** Stable failures; absence and failed business conditions are normal results. */
public enum ErrorCode {
    INVALID_ARGUMENT, TYPE_MISMATCH, VALUE_TOO_LARGE, NUMERIC_OVERFLOW,
    MISSING_VALUE, NOT_READY, OVERLOADED, STORAGE_UNAVAILABLE, STALE_EPOCH,
    SHUTTING_DOWN, UNKNOWN_COMMIT_OUTCOME, IDEMPOTENCY_KEY_REUSED,
    ALREADY_PROCESSED_RESULT_EXPIRED, REQUEST_TIMEOUT, SCHEMA_MISMATCH,
    DURABILITY_UNSAFE, ACCESS_DENIED
}
