[versions]
paper = "1.21.11-R0.1-SNAPSHOT"
postgresql = "42.7.13"
hikari = "6.2.1"
junit = "5.11.4"
placeholderapi = "2.12.3"
skript = "2.16.1"
shadow = "8.3.6"

[libraries]
paper = { module = "io.papermc.paper:paper-api", version.ref = "paper" }
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
hikari = { module = "com.zaxxer:HikariCP", version.ref = "hikari" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-launcher = { module = "org.junit.platform:junit-platform-launcher" }
placeholderapi = { module = "me.clip:placeholderapi", version.ref = "placeholderapi" }
skript = { module = "com.github.SkriptLang:Skript", version.ref = "skript" }

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
